source 'https://rubygems.org'

gem "minitest", require: "minitest/autorun"
gem "activerecord", require: "active_record"
gem "database_cleaner"
gem "pry-byebug"

# Specify your gem's dependencies in api.gemspec
gemspec
